title: "Oceánica Analytics"
logo: "/assets/images/fondo_web.jpg"
description: "Lorena Méndez - Consultora de Datos y Economista"
url: "https://lmendezotero.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

include:
  - pages
