title: "Lorena Méndez Otero"
logo: "/assets/images/fondo.jpg"
description: "Consultora de Datos y Economista"
url: "https://lmendezotero.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: /page:num/

# Sidebar
sidebar:
  nav: "main"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

