title: "Tu Nombre"
logo: "/assets/images/tu-foto.jpg"
description: "Una descripción breve sobre ti."
url: "https://tu_usuario.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: /page:num/

# Sidebar
sidebar:
  nav: "main"

