title: "Nordés Analytics"
description: "Lorena Méndez Otero - Espacio personal para hablar de datos y negocio"
author: Lorena Méndez
logo: "/assets/images/fondo_web.jpg"
header_image: /assets/images/fondo_web.jpg
url: "https://lmendezotero.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  
highlighter: rouge

paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

include:
  - pages
